# Generated by Django 5.1.4 on 2025-01-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('profile_img', models.ImageField(upload_to='profile_images/')),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
