# Generated by Django 5.1.4 on 2025-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_useraccount_about_alter_useraccount_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
