# Generated by Django 5.1.4 on 2025-03-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_useraccount_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
