# Generated by Django 5.1.4 on 2025-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0004_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField()),
                ('user_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
